services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: insurance-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!123
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
volumes:
  sql-data:
